version: '2'
volumes:
  db:
  deps:
  build:

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - 'db:/var/lib/postgresql/data'

  app:
    command: mix phx.server
    build:
      context: ./
    working_dir: /app
    depends_on:
      - db
    volumes:
      - './:/app'
      - 'deps:/app/deps'
      - 'build:/app/_build'
    environment:
      DATABASE_HOST: db
    ports:
      - 4000:4000